# Generated by Django 2.1.1 on 2018-09-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plot_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(blank=True, null=True, upload_to='datasets')),
                ('title', models.CharField(max_length=256)),
                ('no_of_var', models.PositiveIntegerField()),
                ('x_col', models.PositiveIntegerField()),
                ('y_col', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
